# Site settings
title: Kaisa Piipari
header-img: img/home-bg.png
email: kaisa.piipari@gmail.com
copyright_name: kpiipari
description: > # this means to ignore newlines until "baseurl:"
  Pigeon Steps in Tech
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: kaisapii
github_username:  kpiipari
learn_profile: kpiipari
email_username: kaisa.piipari@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
